default_url_options:
  host: tumayun.com
# Email settings
smtp:
  address:              "smtp.gmail.com"
  port:                 587
  domain:               'gmail.com'
  user_name:            'test@gmail.com'
  password:             'test'
  authentication:       'plain'
  enable_starttls_auto:  true
